# Exported from Render on 2024-08-06T22:14:10Z
databases:
  # A Pro database instance with a read replica
  - name: quiviapi # Required
    region: oregon # Default: oregon
    plan: free # Default: starter
    databaseName: quiviapi # Default: generated value based on name
    user: docker # Default: generated value based on name
    ipAllowList: # Default: allows all connections
      - source: 0.0.0.0/0
        description: everywhere
services:
  - type: web
    name: quivi-api
    runtime: node
    repo: https://github.com/MaderG/quivi-api
    plan: free

    envVars:
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: quiviapi
          property: connectionString

    region: oregon
    buildCommand: npm install
    startCommand: node
version: "1"
